// Outcome Intelligence Engine Type Definitions

export enum OutcomeType {
  PROJECT_COMPLETION = 'PROJECT_COMPLETION',
  MILESTONE_ACHIEVED = 'MILESTONE_ACHIEVED',
  BUDGET_ADHERENCE = 'BUDGET_ADHERENCE',
  TIMELINE_ADHERENCE = 'TIMELINE_ADHERENCE',
  CLIENT_SATISFACTION = 'CLIENT_SATISFACTION',
  REPEAT_BUSINESS = 'REPEAT_BUSINESS',
  SCOPE_MANAGEMENT = 'SCOPE_MANAGEMENT',
}

export enum OutcomeRating {
  EXCEPTIONAL = 'EXCEPTIONAL',
  SUCCESSFUL = 'SUCCESSFUL',
  SATISFACTORY = 'SATISFACTORY',
  BELOW_EXPECTATIONS = 'BELOW_EXPECTATIONS',
  UNSUCCESSFUL = 'UNSUCCESSFUL',
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum RiskCategory {
  COMMUNICATION = 'COMMUNICATION',
  TIMELINE = 'TIMELINE',
  BUDGET = 'BUDGET',
  SCOPE = 'SCOPE',
  QUALITY = 'QUALITY',
  RESOURCE = 'RESOURCE',
  RELATIONSHIP = 'RELATIONSHIP',
}

export enum PredictionConfidence {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH',
}

// Outcome Interfaces
export interface EngagementOutcomeCreateInput {
  contractId: string;
  clientId: string;
  freelancerId: string;
  outcomeType: OutcomeType;
  rating: OutcomeRating;
  score: number;
  metrics?: OutcomeMetrics;
  clientFeedback?: string;
  freelancerFeedback?: string;
  lessonsLearned?: string[];
}

export interface OutcomeMetrics {
  budgetVariance?: number;
  timelineVariance?: number;
  scopeChanges?: number;
  communicationScore?: number;
  qualityScore?: number;
  deliverablesMet?: number;
  deliverablesTotal?: number;
}

// Prediction Interfaces
export interface SuccessPredictionInput {
  contractId: string;
  clientId: string;
  freelancerId: string;
  projectType: string;
  budget: number;
  duration: number;
  complexity: 'LOW' | 'MEDIUM' | 'HIGH';
}

export interface PredictionResult {
  successProbability: number;
  confidence: PredictionConfidence;
  riskFactors: RiskFactor[];
  recommendations: string[];
  similarProjectsAnalyzed: number;
}

export interface RiskFactor {
  category: RiskCategory;
  level: RiskLevel;
  description: string;
  mitigation?: string;
}

// Risk Alert Interfaces
export interface RiskAlertCreateInput {
  contractId: string;
  riskCategory: RiskCategory;
  riskLevel: RiskLevel;
  title: string;
  description: string;
  indicators: string[];
  suggestedActions: string[];
  autoGenerated?: boolean;
}

export interface RiskAlertUpdateInput {
  acknowledged?: boolean;
  acknowledgedBy?: string;
  resolved?: boolean;
  resolvedBy?: string;
  resolution?: string;
}

// Analytics Interfaces
export interface FreelancerAnalytics {
  userId: string;
  totalProjects: number;
  successRate: number;
  averageRating: number;
  onTimeDeliveryRate: number;
  budgetAdherenceRate: number;
  repeatClientRate: number;
  strengthAreas: string[];
  improvementAreas: string[];
  recentTrend: 'IMPROVING' | 'STABLE' | 'DECLINING';
}

export interface ClientAnalytics {
  userId: string;
  totalProjects: number;
  averageProjectSize: number;
  averageProjectDuration: number;
  freelancerRetentionRate: number;
  communicationScore: number;
  paymentReliability: number;
  scopeStabilityScore: number;
}

export interface MarketInsights {
  category: string;
  averageRate: number;
  demandTrend: 'RISING' | 'STABLE' | 'FALLING';
  topSkills: string[];
  averageProjectDuration: number;
  successRate: number;
  competitionLevel: 'LOW' | 'MEDIUM' | 'HIGH';
}

// Benchmark Interfaces
export interface BenchmarkData {
  category: string;
  metric: string;
  percentile25: number;
  percentile50: number;
  percentile75: number;
  percentile90: number;
  sampleSize: number;
  calculatedAt: Date;
}

export interface PerformanceComparison {
  metric: string;
  userValue: number;
  marketAverage: number;
  percentileRank: number;
  trend: 'ABOVE' | 'AT' | 'BELOW';
}
