import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  target: 'node20',
  platform: 'node',
  splitting: false,
  sourcemap: true,
  clean: true,
  external: [
    '@prisma/client',
    '.prisma/client',
    '.prisma/client/default',
    '@fastify/cookie',
    '@fastify/cors',
    '@fastify/formbody',
    '@fastify/helmet',
    '@fastify/multipart',
    '@fastify/rate-limit',
    '@fastify/sensible',
    '@fastify/swagger',
    '@fastify/swagger-ui',
    '@skillancer/config',
    '@skillancer/database',
    '@skillancer/logger',
    '@skillancer/metrics',
    '@skillancer/service-client',
    '@skillancer/types',
    '@skillancer/utils',
    'fastify',
    'jsonwebtoken',
    'zod',
  ],
  tsconfig: './tsconfig.json',
});
