import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  target: 'node20',
  platform: 'node',
  splitting: false,
  sourcemap: true,
  clean: true,
  external: [
    '@prisma/client',
    '.prisma/client',
    '.prisma/client/default',
    '@aws-sdk/client-s3',
    '@aws-sdk/s3-request-presigner',
    '@azure/msal-node',
    '@elastic/elasticsearch',
    '@microsoft/microsoft-graph-client',
    '@sinclair/typebox',
    '@skillancer/cache',
    '@skillancer/database',
    '@skillancer/logger',
    '@skillancer/types',
    '@skillancer/utils',
    'bullmq',
    'express',
    'fastify',
    'google-auth-library',
    'googleapis',
    'ioredis',
    'puppeteer',
    'zod',
  ],
  tsconfig: './tsconfig.json',
});
