/**
 * @module @skillancer/database
 * Prisma client and database utilities for Skillancer
 */
export * from './client';
export * from './extensions/soft-delete';
export * from './extensions/audit-log';
export * from './migration-lock';
export type {
  User,
  UserStatus,
  VerificationLevel,
  RefreshToken,
  UserProfile,
  UserSkill,
  SkillLevel,
  Skill,
  PortfolioItem,
  Tenant,
  TenantMember,
  TenantPlan,
  TenantRole,
  Job,
  JobSkill,
  JobStatus,
  JobVisibility,
  BudgetType,
  JobDuration,
  ExperienceLevel,
  Bid,
  BidStatus,
  Contract,
  ContractStatus,
  Milestone,
  MilestoneStatus,
  Service,
  ServiceSkill,
  ServiceStatus,
  Session,
  SessionStatus,
  SessionType,
  Message,
  MessageType,
  Payment,
  PaymentMethod,
  PaymentStatus,
  PaymentType,
  PaymentMethodType,
  PaymentMethodStatus,
  StripeCustomer,
  Invoice,
  InvoiceStatus,
  Review,
  ReviewType,
  ReviewStatus,
  ReviewResponse,
  ReviewHelpfulVote,
  ReviewReport,
  ReviewReportReason,
  ReportStatus,
  ReviewInvitation,
  ReviewInvitationStatus,
  UserRatingAggregation,
  TrustScore,
  TrustScoreHistory,
  SkillPodComplianceRecord,
  TrustScoreThreshold,
  Notification,
  NotificationCategory,
  NotificationPriority,
  NotificationPreference,
  NotificationTemplate,
  NotificationDigest,
  EmailUnsubscribe,
  EmailFrequency,
  DigestType,
  DigestStatus,
  UnsubscribeType,
  AuditLog,
  UserMfa,
  MfaChallenge,
  Product,
  ProductType,
  Price,
  PriceBillingInterval,
  PriceTier,
  PriceUsageType,
  Coupon,
  CouponDiscountType,
  CouponDuration,
  CouponRedemption,
  Subscription,
  SubscriptionProduct,
  BillingInterval,
  SubscriptionStatus,
  SubscriptionInvoice,
  SubscriptionInvoiceStatus,
  UsageRecord,
  UsageAction,
  PayoutAccount,
  PayoutAccountType,
  PayoutAccountStatus,
  PaymentTransaction,
  TransactionType,
  TransactionStatus,
  Payout,
  PayoutStatus,
  HipaaCompliance,
  HipaaComplianceLevel,
  BaaStatus,
  PhiAccessLog,
  PhiAccessType,
  PhiCategory,
  HipaaTraining,
  HipaaTrainingType,
  TrainingStatus,
  BreachIncident,
  BreachIncidentType,
  BreachSeverity,
  BreachStatus,
  BreachTimeline,
  PhiToken,
  PhiFieldType,
  KillSwitchEvent,
  KillSwitchAction,
  AccessRevocation,
  RevocationScope,
  RateDataPoint,
  RateAggregate,
  FreelancerRateHistory,
  RateRecommendation,
  SkillDemandTrend,
  RateSourceType,
  RateType,
  PeriodType,
  RateChangeReason,
  RecommendationType,
  RecommendationStatus,
  DemandLevel,
  ContractTemplate,
  ContractV2,
  ContractMilestoneV2,
  TimeEntryV2,
  ContractAmendment,
  ContractActivity,
  ContractSignature,
  ContractInvoice,
  ContractDispute,
  ContractDisputeMessage,
  ContractSourceType,
  ContractTypeV2,
  RateTypeV2,
  ContractStatusV2,
  MilestoneStatusV2,
  TimeEntryStatusV2,
  EvidenceType,
  AmendmentStatus,
  TerminationType,
  ContractActivityType,
  SignatureType,
  ContractInvoiceStatus,
  ContractDisputeReason,
  ContractDisputeStatus,
  ContractDisputeResolution,
  EscrowAccountV2,
  EscrowTransactionV2,
  InvoiceLineItem,
  EscrowAccountStatusV2,
  EscrowTransactionTypeV2,
  EscrowTransactionStatusV2,
  InvoiceLineItemType,
  ServicePackage,
  ServiceAddOn,
  ServiceOrder,
  ServiceOrderItem,
  ServiceOrderAddOn,
  ServiceDelivery,
  ServiceRevisionRequest,
  ServiceOrderMessage,
  ServiceReview,
  PackageTier,
  ServiceCategory,
  ServiceOrderStatus,
  ServicePaymentStatus,
  ServiceEscrowStatus,
  ServiceMessageType,
  Conversation,
  ConversationParticipant,
  ConversationMessage,
  ConversationMessageReaction,
  ConversationMessageReadReceipt,
  MessageAttachment,
  UserPresence,
  UserBlocklist,
  ConversationType,
  ParticipantRole,
  ConversationContentType,
  ConversationMessageType,
  SystemMessageEventType,
  AttachmentProcessingStatus,
  ScanStatus,
  PresenceStatus,
  Client,
  ClientContact,
  ClientInteraction,
  Opportunity,
  OpportunityActivity,
  ClientDocument,
  ClientReminder,
  CrmCustomField,
  ClientType,
  ClientSource,
  ClientStatus,
  CompanySize,
  ContactRole,
  InteractionType,
  Sentiment,
  OpportunitySource,
  OpportunityStage,
  OpportunityStatus,
  CrmPriority,
  CrmDocumentType,
  ReminderType,
  ReminderStatus,
  CustomFieldType,
  CrmEntityType,
  CockpitProject,
  ProjectTask,
  ProjectMilestone,
  CockpitTimeEntry,
  ProjectFile,
  ProjectActivity,
  ProjectTemplate,
  ProjectSource,
  CockpitProjectType,
  CockpitProjectStatus,
  CockpitBudgetType,
  CockpitTaskStatus,
  CockpitMilestoneStatus,
  ProjectFileType,
  ProjectActivityType,
  TimeEntrySource,
  TimeTrackingSettings,
  ActiveTimer,
  Timesheet,
  TimeCategory,
  TrackingMethod,
  TimeApprovalStatus,
  RoundingMethod,
  TimerStatus,
  TimesheetStatus,
  CalendarConnection,
  ExternalCalendar,
  CalendarEvent,
  AvailabilitySchedule,
  BookingLink,
  Booking,
  CalendarProvider,
  SyncDirection,
  SyncStatus,
  EventSource,
  EventType,
  EventStatus,
  EventVisibility,
  LocationType,
  BookingStatus,
} from '@prisma/client';
export {
  MfaMethod,
  TrustTier,
  TrustTrend,
  ComplianceEventType,
  ComplianceSeverity,
  ThresholdContextType,
  HipaaComplianceLevel as HipaaComplianceLevelEnum,
  BaaStatus as BaaStatusEnum,
  PhiAccessType as PhiAccessTypeEnum,
  PhiCategory as PhiCategoryEnum,
  HipaaTrainingType as HipaaTrainingTypeEnum,
  TrainingStatus as TrainingStatusEnum,
  BreachIncidentType as BreachIncidentTypeEnum,
  BreachSeverity as BreachSeverityEnum,
  BreachStatus as BreachStatusEnum,
  PhiFieldType as PhiFieldTypeEnum,
  ContractSourceType as ContractSourceTypeEnum,
  ContractTypeV2 as ContractTypeV2Enum,
  RateTypeV2 as RateTypeV2Enum,
  ContractStatusV2 as ContractStatusV2Enum,
  MilestoneStatusV2 as MilestoneStatusV2Enum,
  TimeEntryStatusV2 as TimeEntryStatusV2Enum,
  EvidenceType as EvidenceTypeEnum,
  AmendmentStatus as AmendmentStatusEnum,
  TerminationType as TerminationTypeEnum,
  ContractActivityType as ContractActivityTypeEnum,
  SignatureType as SignatureTypeEnum,
  ContractInvoiceStatus as ContractInvoiceStatusEnum,
  ContractDisputeReason as ContractDisputeReasonEnum,
  ContractDisputeStatus as ContractDisputeStatusEnum,
  ContractDisputeResolution as ContractDisputeResolutionEnum,
  EscrowAccountStatusV2 as EscrowAccountStatusV2Enum,
  EscrowTransactionTypeV2 as EscrowTransactionTypeV2Enum,
  EscrowTransactionStatusV2 as EscrowTransactionStatusV2Enum,
  InvoiceLineItemType as InvoiceLineItemTypeEnum,
  ConversationType as ConversationTypeEnum,
  ParticipantRole as ParticipantRoleEnum,
  ConversationContentType as ConversationContentTypeEnum,
  ConversationMessageType as ConversationMessageTypeEnum,
  SystemMessageEventType as SystemMessageEventTypeEnum,
  AttachmentProcessingStatus as AttachmentProcessingStatusEnum,
  ScanStatus as ScanStatusEnum,
  PresenceStatus as PresenceStatusEnum,
  ClientType as ClientTypeEnum,
  ClientSource as ClientSourceEnum,
  ClientStatus as ClientStatusEnum,
  CompanySize as CompanySizeEnum,
  ContactRole as ContactRoleEnum,
  InteractionType as InteractionTypeEnum,
  Sentiment as SentimentEnum,
  OpportunitySource as OpportunitySourceEnum,
  OpportunityStage as OpportunityStageEnum,
  OpportunityStatus as OpportunityStatusEnum,
  CrmPriority as CrmPriorityEnum,
  CrmDocumentType as CrmDocumentTypeEnum,
  ReminderType as ReminderTypeEnum,
  ReminderStatus as ReminderStatusEnum,
  CustomFieldType as CustomFieldTypeEnum,
  CrmEntityType as CrmEntityTypeEnum,
  ProjectSource as ProjectSourceEnum,
  CockpitProjectType as CockpitProjectTypeEnum,
  CockpitProjectStatus as CockpitProjectStatusEnum,
  CockpitBudgetType as CockpitBudgetTypeEnum,
  CockpitTaskStatus as CockpitTaskStatusEnum,
  CockpitMilestoneStatus as CockpitMilestoneStatusEnum,
  ProjectFileType as ProjectFileTypeEnum,
  ProjectActivityType as ProjectActivityTypeEnum,
  TimeEntrySource as TimeEntrySourceEnum,
  TrackingMethod as TrackingMethodEnum,
  TimeApprovalStatus as TimeApprovalStatusEnum,
  RoundingMethod as RoundingMethodEnum,
  TimerStatus as TimerStatusEnum,
  TimesheetStatus as TimesheetStatusEnum,
  CalendarProvider as CalendarProviderEnum,
  SyncDirection as SyncDirectionEnum,
  SyncStatus as SyncStatusEnum,
  EventSource as EventSourceEnum,
  EventType as EventTypeEnum,
  EventStatus as EventStatusEnum,
  EventVisibility as EventVisibilityEnum,
  LocationType as LocationTypeEnum,
  BookingStatus as BookingStatusEnum,
} from '@prisma/client';
//# sourceMappingURL=index.d.ts.map
