import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  target: 'node20',
  platform: 'node',
  splitting: false,
  sourcemap: true,
  clean: true,
  external: [
    '@prisma/client',
    '.prisma/client',
    '.prisma/client/default',
    '@fastify/cors',
    '@fastify/helmet',
    '@fastify/jwt',
    '@fastify/rate-limit',
    '@fastify/sensible',
    '@fastify/swagger',
    '@fastify/swagger-ui',
    '@fastify/under-pressure',
    'dotenv',
    'fastify',
    'fastify-plugin',
    'pino',
    'pino-pretty',
    'zod',
  ],
  tsconfig: './tsconfig.json',
});
