/**
 * @module @skillancer/database
 * Prisma client and database utilities for Skillancer
 */

// Core client
export * from './client';

// Extensions
export * from './extensions/soft-delete';
export * from './extensions/audit-log';

// Migration utilities
export * from './migration-lock';

// Types (re-exported from Prisma)
export type {
  User,
  UserStatus,
  VerificationLevel,
  RefreshToken,
  UserProfile,
  UserSkill,
  SkillLevel,
  Skill,
  PortfolioItem,
  Tenant,
  TenantMember,
  TenantPlan,
  TenantRole,
  Job,
  JobSkill,
  JobStatus,
  JobVisibility,
  BudgetType,
  JobDuration,
  ExperienceLevel,
  Bid,
  BidStatus,
  Contract,
  ContractStatus,
  Milestone,
  MilestoneStatus,
  Service,
  ServiceSkill,
  ServiceStatus,
  Session,
  SessionStatus,
  SessionType,
  Message,
  MessageType,
  Payment,
  PaymentMethod,
  PaymentStatus,
  PaymentType,
  PaymentMethodType,
  PaymentMethodStatus,
  StripeCustomer,
  TenantBillingInvoice,
  TenantBillingInvoiceStatus,
  // Review types
  Review,
  ReviewType,
  ReviewStatus,
  ReviewResponse,
  ReviewHelpfulVote,
  ReviewReport,
  ReviewReportReason,
  ReportStatus,
  ReviewInvitation,
  ReviewInvitationStatus,
  UserRatingAggregation,
  // Trust Score types
  TrustScore,
  TrustScoreHistory,
  SkillPodComplianceRecord,
  TrustScoreThreshold,
  Notification,
  NotificationCategory,
  NotificationPriority,
  AuditLog,
  UserMfa,
  MfaChallenge,
  // Product and Pricing types
  Product,
  ProductType,
  Price,
  PriceBillingInterval,
  PriceTier,
  PriceUsageType,
  // Coupon types
  Coupon,
  CouponDiscountType,
  CouponDuration,
  CouponRedemption,
  // Subscription types
  Subscription,
  SubscriptionProduct,
  BillingInterval,
  SubscriptionStatus,
  SubscriptionInvoice,
  SubscriptionInvoiceStatus,
  UsageRecord,
  UsageAction,
  // Payout and Transaction types
  PayoutAccount,
  PayoutAccountType,
  PayoutAccountStatus,
  PaymentTransaction,
  TransactionType,
  TransactionStatus,
  Payout,
  PayoutStatus,
  // HIPAA Compliance types
  HipaaCompliance,
  HipaaComplianceLevel,
  BaaStatus,
  PhiAccessLog,
  PhiAccessType,
  PhiCategory,
  HipaaTraining,
  HipaaTrainingType,
  TrainingStatus,
  BreachIncident,
  BreachIncidentType,
  BreachSeverity,
  BreachStatus,
  BreachTimeline,
  PhiToken,
  PhiFieldType,
  // Kill Switch types
  KillSwitchEvent,
  KillSwitchAction,
  AccessRevocation,
  RevocationScope,
  // Rate Intelligence types
  RateDataPoint,
  RateAggregate,
  FreelancerRateHistory,
  RateRecommendation,
  SkillDemandTrend,
  RateSourceType,
  RateType,
  PeriodType,
  RateChangeReason,
  RecommendationType,
  RecommendationStatus,
  DemandLevel,
  // Contract Management V2 types
  ContractTemplate,
  ContractV2,
  ContractMilestoneV2,
  TimeEntryV2,
  ContractAmendment,
  ContractActivity,
  ContractSignature,
  ContractInvoice,
  ContractDispute,
  ContractDisputeMessage,
  ContractSourceType,
  ContractTypeV2,
  RateTypeV2,
  ContractStatusV2,
  MilestoneStatusV2,
  TimeEntryStatusV2,
  EvidenceType,
  AmendmentStatus,
  TerminationType,
  ContractActivityType,
  SignatureType,
  ContractInvoiceStatus,
  ContractDisputeReason,
  ContractDisputeStatus,
  ContractDisputeResolution,
  // Escrow V2 types
  EscrowAccountV2,
  EscrowTransactionV2,
  ContractInvoiceLineItem,
  EscrowAccountStatusV2,
  EscrowTransactionTypeV2,
  EscrowTransactionStatusV2,
  InvoiceLineItemType,
  // Service types
  ServicePackage,
  ServiceAddOn,
  ServiceOrder,
  ServiceOrderItem,
  ServiceOrderAddOn,
  ServiceDelivery,
  ServiceRevisionRequest,
  ServiceOrderMessage,
  ServiceReview,
  PackageTier,
  ServiceCategory,
  ServiceOrderStatus,
  ServicePaymentStatus,
  ServiceEscrowStatus,
  ServiceMessageType,
  // Cockpit Client & Project types
  Client,
  ClientContact,
  ClientInteraction,
  ClientDocument,
  ClientReminder,
  ClientStatus,
  ClientType,
  ClientSource,
  InteractionType,
  CrmDocumentType,
  CrmPriority,
  ReminderType,
  ReminderStatus,
  CockpitProject,
  CockpitProjectStatus,
  CockpitProjectType,
  CockpitBudgetType,
  CockpitTaskStatus,
  // Cockpit Integration types
  Integration,
  IntegrationProvider,
  IntegrationStatus,
  SyncFrequency,
  IntegrationSyncStatus,
  IntegrationMapping,
  MappingEntityType,
  IntegrationSyncLog,
  IntegrationTemplate,
  WebhookEvent,
  WebhookEventStatus,
  // Cockpit Financial types
  FinancialAccount,
  FinancialAccountType,
  FinancialTransaction,
  FinancialTransactionType,
  FinancialTransactionSource,
  FinancialTransactionStatus,
  RecurringTransaction,
  RecurrenceFrequency,
  TransactionCategory,
  FinancialGoal,
  FinancialGoalType,
  FinancialGoalStatus,
  FinancialPeriodType,
  MileageLog,
  MileagePurpose,
  TaxProfile,
  BusinessType,
  FilingStatus,
  AccountingMethod,
  // Cockpit Invoice types (exported both as-is and with Cockpit prefix for clarity)
  Invoice,
  InvoiceLineItem,
  InvoicePayment,
  InvoiceTemplate,
  RecurringInvoice,
  InvoiceActivity,
  InvoiceSettings,
  InvoiceStatus,
  LineItemType,
  DiscountType,
  LateFeeType,
  InvoicePaymentMethod,
  InvoicePaymentStatus,
  TemplateLayout,
  InvoiceActivityType,
} from '@prisma/client';

// Prisma namespace is already exported via client.ts

// Enums (re-exported from Prisma - using value import for runtime access)
// Export with BOTH original names (for service imports) and Enum-suffixed aliases
export {
  MfaMethod,
  TrustTier,
  TrustTrend,
  ComplianceEventType,
  ComplianceSeverity,
  ThresholdContextType,
  // HIPAA enums — both original and aliased names
  HipaaComplianceLevel,
  HipaaComplianceLevel as HipaaComplianceLevelEnum,
  BaaStatus,
  BaaStatus as BaaStatusEnum,
  PhiAccessType,
  PhiAccessType as PhiAccessTypeEnum,
  PhiCategory,
  PhiCategory as PhiCategoryEnum,
  HipaaTrainingType,
  HipaaTrainingType as HipaaTrainingTypeEnum,
  TrainingStatus,
  TrainingStatus as TrainingStatusEnum,
  BreachIncidentType,
  BreachIncidentType as BreachIncidentTypeEnum,
  BreachSeverity,
  BreachSeverity as BreachSeverityEnum,
  BreachStatus,
  BreachStatus as BreachStatusEnum,
  PhiFieldType,
  PhiFieldType as PhiFieldTypeEnum,
  // Contract Management V2 enums
  ContractSourceType,
  ContractSourceType as ContractSourceTypeEnum,
  ContractTypeV2,
  ContractTypeV2 as ContractTypeV2Enum,
  RateTypeV2,
  RateTypeV2 as RateTypeV2Enum,
  ContractStatusV2,
  ContractStatusV2 as ContractStatusV2Enum,
  MilestoneStatusV2,
  MilestoneStatusV2 as MilestoneStatusV2Enum,
  TimeEntryStatusV2,
  TimeEntryStatusV2 as TimeEntryStatusV2Enum,
  EvidenceType,
  EvidenceType as EvidenceTypeEnum,
  AmendmentStatus,
  AmendmentStatus as AmendmentStatusEnum,
  TerminationType,
  TerminationType as TerminationTypeEnum,
  ContractActivityType,
  ContractActivityType as ContractActivityTypeEnum,
  SignatureType,
  SignatureType as SignatureTypeEnum,
  ContractInvoiceStatus,
  ContractInvoiceStatus as ContractInvoiceStatusEnum,
  ContractDisputeReason,
  ContractDisputeReason as ContractDisputeReasonEnum,
  ContractDisputeStatus,
  ContractDisputeStatus as ContractDisputeStatusEnum,
  ContractDisputeResolution,
  ContractDisputeResolution as ContractDisputeResolutionEnum,
  // Escrow V2 enums
  EscrowAccountStatusV2,
  EscrowAccountStatusV2 as EscrowAccountStatusV2Enum,
  EscrowTransactionTypeV2,
  EscrowTransactionTypeV2 as EscrowTransactionTypeV2Enum,
  EscrowTransactionStatusV2,
  EscrowTransactionStatusV2 as EscrowTransactionStatusV2Enum,
  InvoiceLineItemType,
  InvoiceLineItemType as InvoiceLineItemTypeEnum,
  // Cockpit Client & Project enums
  ClientStatus,
  ClientStatus as ClientStatusEnum,
  ClientType,
  ClientType as ClientTypeEnum,
  ClientSource,
  ClientSource as ClientSourceEnum,
  InteractionType,
  InteractionType as InteractionTypeEnum,
  CrmDocumentType,
  CrmDocumentType as CrmDocumentTypeEnum,
  CrmPriority,
  CrmPriority as CrmPriorityEnum,
  ReminderType,
  ReminderType as ReminderTypeEnum,
  ReminderStatus,
  ReminderStatus as ReminderStatusEnum,
  CockpitProjectStatus,
  CockpitProjectStatus as CockpitProjectStatusEnum,
  CockpitProjectType,
  CockpitProjectType as CockpitProjectTypeEnum,
  CockpitBudgetType,
  CockpitBudgetType as CockpitBudgetTypeEnum,
  CockpitTaskStatus,
  CockpitTaskStatus as CockpitTaskStatusEnum,
  // Cockpit Integration enums
  IntegrationProvider,
  IntegrationProvider as IntegrationProviderEnum,
  IntegrationStatus,
  IntegrationStatus as IntegrationStatusEnum,
  SyncFrequency,
  SyncFrequency as SyncFrequencyEnum,
  IntegrationSyncStatus,
  IntegrationSyncStatus as IntegrationSyncStatusEnum,
  MappingEntityType,
  MappingEntityType as MappingEntityTypeEnum,
  WebhookEventStatus,
  WebhookEventStatus as WebhookEventStatusEnum,
  // Cockpit Financial enums
  FinancialAccountType,
  FinancialAccountType as FinancialAccountTypeEnum,
  FinancialTransactionType,
  FinancialTransactionType as FinancialTransactionTypeEnum,
  FinancialTransactionSource,
  FinancialTransactionSource as FinancialTransactionSourceEnum,
  FinancialTransactionStatus,
  FinancialTransactionStatus as FinancialTransactionStatusEnum,
  RecurrenceFrequency,
  RecurrenceFrequency as RecurrenceFrequencyEnum,
  FinancialGoalType,
  FinancialGoalType as FinancialGoalTypeEnum,
  FinancialGoalStatus,
  FinancialGoalStatus as FinancialGoalStatusEnum,
  FinancialPeriodType,
  FinancialPeriodType as FinancialPeriodTypeEnum,
  MileagePurpose,
  MileagePurpose as MileagePurposeEnum,
  BusinessType,
  BusinessType as BusinessTypeEnum,
  FilingStatus,
  FilingStatus as FilingStatusEnum,
  AccountingMethod,
  AccountingMethod as AccountingMethodEnum,
  // Cockpit Invoice enums
  InvoiceStatus,
  InvoiceStatus as InvoiceStatusEnum,
  LineItemType,
  LineItemType as LineItemTypeEnum,
  DiscountType,
  DiscountType as DiscountTypeEnum,
  LateFeeType,
  LateFeeType as LateFeeTypeEnum,
  InvoicePaymentMethod,
  InvoicePaymentMethod as InvoicePaymentMethodEnum,
  InvoicePaymentStatus,
  InvoicePaymentStatus as InvoicePaymentStatusEnum,
  TemplateLayout,
  TemplateLayout as TemplateLayoutEnum,
  InvoiceActivityType,
  InvoiceActivityType as InvoiceActivityTypeEnum,
  // Additional enums used by services
  UserStatus,
  VerificationLevel,
  JobStatus,
  JobVisibility,
  BidStatus,
  ContractStatus,
  MilestoneStatus,
  PaymentStatus,
  PaymentType,
  ServiceStatus,
  SessionStatus,
  SessionType,
  NotificationCategory,
  NotificationPriority,
  SkillLevel,
  BudgetType,
  JobDuration,
  ExperienceLevel,
  ReviewType,
  ReviewStatus,
  ReviewReportReason,
  ReportStatus,
  ReviewInvitationStatus,
  TenantRole,
  TenantPlan,
  PaymentMethodType,
  PaymentMethodStatus,
  PayoutAccountType,
  PayoutAccountStatus,
  TransactionType,
  TransactionStatus,
  PayoutStatus,
  SubscriptionStatus,
  ProductType,
  PriceBillingInterval,
  PriceUsageType,
  BillingInterval,
  CouponDiscountType,
  CouponDuration,
  MessageType,
  TenantBillingInvoiceStatus,
  SubscriptionInvoiceStatus,
  UsageAction,
  // Kill Switch enums
  KillSwitchAction,
  RevocationScope,
  // Rate Intelligence enums
  RateSourceType,
  RateType,
  PeriodType,
  RateChangeReason,
  RecommendationType,
  RecommendationStatus,
  DemandLevel,
  // Service marketplace enums
  PackageTier,
  ServiceCategory,
  ServiceOrderStatus,
  ServicePaymentStatus,
  ServiceEscrowStatus,
  ServiceMessageType,
  // Unified Financial / Report enums
  FinancialReportType,
  FinancialReportType as FinancialReportTypeEnum,
  FinancialReportStatus,
  FinancialReportStatus as FinancialReportStatusEnum,
  UnifiedTransactionSource,
  UnifiedTransactionSource as UnifiedTransactionSourceEnum,
  UnifiedTransactionType,
  UnifiedTransactionType as UnifiedTransactionTypeEnum,
  UnifiedSyncStatus,
  UnifiedSyncStatus as UnifiedSyncStatusEnum,
  // Learning enums
  LearningGoalType,
  LearningGoalType as LearningGoalTypeEnum,
  GoalPeriodType,
  GoalPeriodType as GoalPeriodTypeEnum,
  GoalStatus,
  GoalStatus as GoalStatusEnum,
} from '@prisma/client';
