/**
 * @module @skillancer/database
 * Prisma client and database utilities for Skillancer
 */

// Core client
export * from './client';

// Extensions
export * from './extensions/soft-delete';
export * from './extensions/audit-log';

// Migration utilities
export * from './migration-lock';

// Types (re-exported from Prisma)
export type {
  User,
  UserStatus,
  VerificationLevel,
  RefreshToken,
  UserProfile,
  UserSkill,
  SkillLevel,
  Skill,
  PortfolioItem,
  Tenant,
  TenantMember,
  TenantPlan,
  TenantRole,
  Job,
  JobSkill,
  JobStatus,
  JobVisibility,
  BudgetType,
  JobDuration,
  ExperienceLevel,
  Bid,
  BidStatus,
  Contract,
  ContractStatus,
  Milestone,
  MilestoneStatus,
  Service,
  ServiceSkill,
  ServiceStatus,
  Session,
  SessionStatus,
  SessionType,
  Message,
  MessageType,
  Payment,
  PaymentMethod,
  PaymentStatus,
  PaymentType,
  PaymentMethodType,
  PaymentMethodStatus,
  StripeCustomer,
  Invoice,
  InvoiceStatus,
  // Review types
  Review,
  ReviewType,
  ReviewStatus,
  ReviewResponse,
  ReviewHelpfulVote,
  ReviewReport,
  ReviewReportReason,
  ReportStatus,
  ReviewInvitation,
  ReviewInvitationStatus,
  UserRatingAggregation,
  // Trust Score types
  TrustScore,
  TrustScoreHistory,
  SkillPodComplianceRecord,
  TrustScoreThreshold,
  Notification,
  NotificationType,
  NotificationChannel,
  AuditLog,
  UserMfa,
  MfaChallenge,
  // Product and Pricing types
  Product,
  ProductType,
  Price,
  PriceBillingInterval,
  PriceTier,
  PriceUsageType,
  // Coupon types
  Coupon,
  CouponDiscountType,
  CouponDuration,
  CouponRedemption,
  // Subscription types
  Subscription,
  SubscriptionProduct,
  BillingInterval,
  SubscriptionStatus,
  SubscriptionInvoice,
  SubscriptionInvoiceStatus,
  UsageRecord,
  UsageAction,
  // Payout and Transaction types
  PayoutAccount,
  PayoutAccountType,
  PayoutAccountStatus,
  PaymentTransaction,
  TransactionType,
  TransactionStatus,
  Payout,
  PayoutStatus,
  // HIPAA Compliance types
  HipaaCompliance,
  HipaaComplianceLevel,
  BaaStatus,
  PhiAccessLog,
  PhiAccessType,
  PhiCategory,
  HipaaTraining,
  HipaaTrainingType,
  TrainingStatus,
  BreachIncident,
  BreachIncidentType,
  BreachSeverity,
  BreachStatus,
  BreachTimeline,
  PhiToken,
  PhiFieldType,
  // Kill Switch types
  KillSwitchEvent,
  KillSwitchAction,
  AccessRevocation,
  RevocationScope,
  // Rate Intelligence types
  RateDataPoint,
  RateAggregate,
  FreelancerRateHistory,
  RateRecommendation,
  SkillDemandTrend,
  RateSourceType,
  RateType,
  PeriodType,
  RateChangeReason,
  RecommendationType,
  RecommendationStatus,
  DemandLevel,
  // Contract Management V2 types
  ContractTemplate,
  ContractV2,
  ContractMilestoneV2,
  TimeEntryV2,
  ContractAmendment,
  ContractActivity,
  ContractSignature,
  ContractInvoice,
  ContractDispute,
  ContractDisputeMessage,
  ContractSourceType,
  ContractTypeV2,
  RateTypeV2,
  ContractStatusV2,
  MilestoneStatusV2,
  TimeEntryStatusV2,
  EvidenceType,
  AmendmentStatus,
  TerminationType,
  ContractActivityType,
  SignatureType,
  ContractInvoiceStatus,
  ContractDisputeReason,
  ContractDisputeStatus,
  ContractDisputeResolution,
  // Escrow V2 types
  EscrowAccountV2,
  EscrowTransactionV2,
  InvoiceLineItem,
  EscrowAccountStatusV2,
  EscrowTransactionTypeV2,
  EscrowTransactionStatusV2,
  InvoiceLineItemType,
  // Service types
  ServicePackage,
  ServiceAddOn,
  ServiceOrder,
  ServiceOrderItem,
  ServiceOrderAddOn,
  ServiceDelivery,
  ServiceRevisionRequest,
  ServiceOrderMessage,
  ServiceReview,
  PackageTier,
  ServiceCategory,
  ServiceOrderStatus,
  ServicePaymentStatus,
  ServiceEscrowStatus,
  ServiceMessageType,
} from '@prisma/client';

// Prisma namespace is already exported via client.ts

// Enums (re-exported from Prisma - using value import for runtime access)
export {
  MfaMethod,
  TrustTier,
  TrustTrend,
  ComplianceEventType,
  ComplianceSeverity,
  ThresholdContextType,
  // HIPAA enums
  HipaaComplianceLevel as HipaaComplianceLevelEnum,
  BaaStatus as BaaStatusEnum,
  PhiAccessType as PhiAccessTypeEnum,
  PhiCategory as PhiCategoryEnum,
  HipaaTrainingType as HipaaTrainingTypeEnum,
  TrainingStatus as TrainingStatusEnum,
  BreachIncidentType as BreachIncidentTypeEnum,
  BreachSeverity as BreachSeverityEnum,
  BreachStatus as BreachStatusEnum,
  PhiFieldType as PhiFieldTypeEnum,
  // Contract Management V2 enums
  ContractSourceType as ContractSourceTypeEnum,
  ContractTypeV2 as ContractTypeV2Enum,
  RateTypeV2 as RateTypeV2Enum,
  ContractStatusV2 as ContractStatusV2Enum,
  MilestoneStatusV2 as MilestoneStatusV2Enum,
  TimeEntryStatusV2 as TimeEntryStatusV2Enum,
  EvidenceType as EvidenceTypeEnum,
  AmendmentStatus as AmendmentStatusEnum,
  TerminationType as TerminationTypeEnum,
  ContractActivityType as ContractActivityTypeEnum,
  SignatureType as SignatureTypeEnum,
  ContractInvoiceStatus as ContractInvoiceStatusEnum,
  ContractDisputeReason as ContractDisputeReasonEnum,
  ContractDisputeStatus as ContractDisputeStatusEnum,
  ContractDisputeResolution as ContractDisputeResolutionEnum,
  // Escrow V2 enums
  EscrowAccountStatusV2 as EscrowAccountStatusV2Enum,
  EscrowTransactionTypeV2 as EscrowTransactionTypeV2Enum,
  EscrowTransactionStatusV2 as EscrowTransactionStatusV2Enum,
  InvoiceLineItemType as InvoiceLineItemTypeEnum,
} from '@prisma/client';
