/**
 * @module @skillancer/api-client/services
 * Service client exports
 */

export {
  AuthServiceClient,
  createAuthServiceClient,
  type LoginCredentials,
  type RegisterData,
  type AuthTokens,
  type UserProfile as AuthUserProfile,
  type AuthUser,
  type LoginResponse,
  type RegisterResponse,
  type RefreshResponse,
  type ForgotPasswordRequest,
  type ResetPasswordRequest,
  type ChangePasswordRequest,
  type VerifyMfaRequest,
  type EnableMfaResponse,
  type VerifyEmailResponse,
} from './auth';

export {
  UserServiceClient,
  createUserServiceClient,
  type UserProfile,
  type FreelancerProfile,
  type ClientProfile,
  type Skill,
  type Experience,
  type Education,
  type Certification,
  type PortfolioItem,
  type FreelancerStats,
  type CompanyInfo,
  type UpdateProfileRequest,
  type UpdateFreelancerProfileRequest,
  type NotificationSettings,
  type PrivacySettings,
} from './user';

export {
  JobServiceClient,
  createJobServiceClient,
  type Job,
  type JobCategory,
  type JobBudget,
  type JobDuration,
  type JobStatus,
  type CreateJobRequest,
  type UpdateJobRequest,
  type JobSearchParams,
  type JobSearchResult,
  type Proposal,
  type ProposalMilestone,
  type ProposalStatus,
  type CreateProposalRequest,
  type UpdateProposalRequest,
  type Contract,
  type ContractMilestone,
  type ContractStatus,
  type CreateContractRequest,
} from './job';

export {
  MessagingServiceClient,
  createMessagingServiceClient,
  type Conversation,
  type ConversationParticipant,
  type Message,
  type MessageType,
  type MessageStatus,
  type MessageAttachment,
  type CreateConversationRequest,
  type SendMessageRequest,
  type UpdateMessageRequest,
  type ConversationListParams,
  type MessageListParams,
  type TypingIndicator,
} from './messaging';

export {
  BillingServiceClient,
  createBillingServiceClient,
  type PaymentMethod,
  type AddCardRequest,
  type AddBankAccountRequest,
  type Wallet,
  type Transaction,
  type TransactionType,
  type TransactionStatus,
  type Invoice,
  type InvoiceLineItem,
  type InvoiceStatus,
  type CreateInvoiceRequest,
  type Escrow,
  type EscrowStatus,
  type WithdrawalRequest,
  type Withdrawal,
  type WithdrawalStatus,
  type SubscriptionPlan,
  type Subscription,
  type SubscriptionStatus,
} from './billing';
